on: [ pull_request ]

name: Unit tests
jobs:
  backend:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4', '8.0', '8.1']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: Run unit tests
        run: vendor/bin/phpunit --testdox